name: Proxy Auto-Update

on:
  schedule:
    - cron: '0 */12 * * *' # Запуск раз в 12 часов (в полночь и в полдень)
  workflow_dispatch:      # Кнопка для ручного запуска (Слава, используй её, если прокси вдруг сдохли раньше времени)

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Engine
        env:
          MY_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Sync to distributor.txt
        run: |
          # Копируем самый сок (26-й файл) в твой основной файл
          if [ -f githubmirror/26.txt ]; then
            cat githubmirror/26.txt > distributor.txt
            echo "✅ distributor.txt успешно обновлен"
          fi

      - name: Push Results
        run: |
          git config --global user.name 'Catsss3'
          git config --global user.email 'action@github.com'
          git add githubmirror/*.txt distributor.txt README.md
          git commit -m "🚀 Плановое обновление прокси (12ч): $(date)" || echo "No changes"
          git push origin main --force
